import {chromium} from '@playwright/test';
const dir = (process.env.OUT ?? 'artifacts');
const url = process.env.URL ?? (process.env.URL ?? 'https://127.0.0.1:5180') + '/';
const browser = await chromium.launch({headless: true, channel: 'chromium', args: ['--enable-unsafe-webgpu', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required']});
const page = await browser.newPage({viewport: {width: 1100, height: 760}, ignoreHTTPSErrors: true});
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.goto(url + '?quality=low');
await page.locator('#start:not([disabled])').waitFor({timeout: 120000});
await page.locator('#start').click();
await page.waitForTimeout(500);
const dur = await page.evaluate(() => window.burning.snapshot().score.duration);
await page.evaluate((t) => window.burning.seek(t - 2), dur);
await page.evaluate(() => window.burning.togglePause());
await page.waitForTimeout(9000);
const box = await page.locator('.credits').boundingBox();
await page.screenshot({path: `${dir}/credits-final.png`, clip: {x: box.x - 10, y: box.y - 10, width: box.width + 20, height: box.height + 20}});
console.log('links:', await page.evaluate(() => [...document.querySelectorAll('.credits a')].map((a) => `${a.textContent} -> ${a.getAttribute('href')}`)));
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
